server:
  workers: 2
  node:
    environment: production
    dataDir: /presto/etc/data
  log:
    com.facebook.presto: INFO
    io.iguaz.v3io: INFO
    io.iguaz.v3io.daemon: INFO
  config:
    mapPath: /etc/config/presto
    path: /presto/etc
    http:
      port: 8080
    https:
      port: 8443
      keystoreBinary:
      keystore: /var/run/iguazio/java/cert/iguazio.jks
      passphrase:
      image:
        repository: iguaziodocker/base
        tag: 3.0.0
        pullPolicy: IfNotPresent
    query:
      maxMemory: "4GB"
      maxMemoryPerNode: "1GB"
    extra: {}

  jvm:
    maxHeapSize: "8G"
    gcMethod:
      type: "UseG1GC"
      g1:
        heapRegionSize: "32M"
hive:
  metastore:
    hostname: hive
    port: 9083
    
environment:
  template: v3io-configs.deployment.env

volumes:
  coordinator:
    volumesTemplate: v3io-configs.deployment.mount
    volumeMountsTemplate: v3io-configs.deployment.volumeMounts
  worker:
    volumesTemplate: v3io-configs.deployment.mount
    volumeMountsTemplate: v3io-configs.deployment.volumeMounts

image:
  repository: iguaziodocker/presto
  tag: 0.189-1.7.0
  pullPolicy: IfNotPresent
  command: /etc/config/v3io/v3io-presto.sh

service:
  type: ClusterIP
  https:
    createTLS: false
    keyBinary:
    certBinary:

global:
  v3io:
    configMountPath: /etc/config/v3io

v3io: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
