apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-v3io-config
  labels:
    app: {{ template "hive.name" . }}
    chart: {{ template "hive.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ include "v3io-configs.java.configMap" . | indent 2 }}

  health_check.sh: |
{{ include "v3io-configs.script.javaHealthCheck" . | indent 4 }}
    # Check if service is listening on the specified protocol and port
    PROTOCOL="tcp"
    HOST="127.0.0.1"
    SOCKET_PORT={{ .Values.metastore.containerPort }}

    for i in "$@"
    do
    case $i in
        -t=*|--type=*)
        PROTOCOL="${i#*=}"
        ;;
        -h=*|--host=*)
        HOST="${i#*=}"
        ;;
        -p=*|--socket-port=*)
        SOCKET_PORT="${i#*=}"
        ;;
    esac
    done

    RC=echo < /dev/$PROTOCOL/$HOST/$SOCKET_PORT
    if [ "$RC" -ne "0" ]; then
      echo "Unable to communicate with [$HOST:$SOCKET_PORT] over [$PROTOCOL]."
      exit $RC
    fi

  v3io-hive.sh: |
    #!/usr/bin/env bash
    set -e

    echo alias ll=\"ls -lah --color\" >> $HOME/.bash_aliases

{{ include "v3io-configs.script.lookupService" . | indent 4 }}

    cp {{ .Values.global.v3io.configPath }}/hive-site.xml $HIVE_CONF_DIR/

    # Initialize Hive metastore database
    # Check if schema does not exists or invalid, then try to initialize Hive metastore database schema
    set +e
    $HIVE_HOME/bin/schematool -dbType $HIVE_DB_TYPE -validate
    RC=$?
    set -e
    if [ $RC != 0 ]; then
      echo "Hive schema didn't pass validation. RC=$RC"
      echo "Initializing Hive metastore schema..."
      $HIVE_HOME/bin/schematool -initSchema -dbType $HIVE_DB_TYPE
      RC=$?
      if [ $RC != 0 ]; then
        echo "Failed to initialize Hive metastore database schema. RC=$RC"
        exit $RC
      else
        echo "Hive metastore schema initialized successfully."
      fi
    else
      echo "Hive metastore schema already exists. Details:"
      $HIVE_HOME/bin/schematool -dbType $HIVE_DB_TYPE -info
    fi

    echo Starting hive metastore service....
    $HIVE_HOME/bin/hive --service metastore

  hive-site.xml: |
    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
{{ if eq .Values.metastore.database.type "postgresql" }}
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:postgresql://{{ .Values.metastore.database.hostname }}:{{ .Values.metastore.database.port }}/{{ .Values.metastore.database.name }}</value>
      </property>

      <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.postgresql.Driver</value>
      </property>
{{ else }}
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:mysql://{{ .Values.metastore.database.hostname }}:{{ .Values.metastore.database.port }}/{{ .Values.metastore.database.name }}</value>
      </property>

      <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.mariadb.jdbc.Driver</value>
      </property>
{{ end }}

      <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>{{ .Values.metastore.database.username }}</value>
      </property>

      <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>{{ .Values.metastore.database.password }}</value>
      </property>

      <property>
        <name>hive.metastore.uris</name>
        <value>thrift://{{ template "hive.fullname" . }}:{{ .Values.metastore.containerPort }}</value>
        <description>IP address (or fully-qualified domain name) and port of the metastore host</description>
      </property>

      <property>
        <name>hive.metastore.schema.verification</name>
        <value>true</value>
      </property>
    </configuration>
