{{- if eq .Values.httpDB.dbType "mysql" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mlrun.db.initConfigMapName" . }}
  labels:
    {{- include "mlrun.db.labels" . | nindent 4 }}
data:
  enable-root-remote-access.sql: |
    -- Allow passwordless (insecure) access to root user from anywhere
    CREATE USER IF NOT EXISTS 'root'@'%';
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
    FLUSH PRIVILEGES;
    CREATE DATABASE IF NOT EXISTS mlrun;
    {{- if and .Values.modelMonitoring.provisionDB (not .Values.modelMonitoring.dsn)}}
    CREATE DATABASE IF NOT EXISTS mlrun_monitoring;
    {{- end }}
{{- end }}