apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlrun.ui.fullname" . }}
  labels:
    {{- include "mlrun.ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      {{- include "mlrun.ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mlrun.ui.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.ui.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.ui.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ template "mlrun.name" . }}-{{ .Values.ui.name }}
          securityContext:
            {{- toYaml .Values.ui.securityContext | nindent 12 }}
          image: '{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}'
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
          - name: MLRUN_API_PROXY_URL
            value: 'http://{{ include "mlrun.api.fullname" . }}:{{ .Values.api.service.port }}'
          {{- if .Values.nuclioDashboardURL }}
          - name: NUCLIO_API_PROXY_URL
            value: {{ .Values.nuclioDashboardURL }}
          {{- end }}
          {{- if .Values.ui.extraEnv }}
          {{ toYaml .Values.ui.extraEnv | nindent 10 }}
          {{- end }}
          {{- if .Values.ui.envFrom }}
          envFrom:
          {{ toYaml .Values.ui.envFrom | nindent 10 }}
          {{- end }}
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
