kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "v3iod.cache.name" . }}
  labels:
    app: {{ template "v3iod.name" . }}
    chart: {{ template "v3iod.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: locator
spec:
  template:
    metadata:
      labels:
        app: {{ template "v3iod.name" . }}
        chart: {{ template "v3iod.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: locator
    spec:
      serviceAccountName: {{ template "v3iod.cache.name" . }}
      containers:
        - name: rest-locator
          image: image: {{ .Values.locator.image.repository }}:{{ .Values.locator.image.tag }}
          imagePullPolicy: {{ .Values.locator.image.pullPolicy | quote }}
          command: ["/bin/bash", "-c"]
          args:
            - registryctl --namespace=$CURRENT_NAMESPACE
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "100Mi"
          env:
            - name: CURRENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
