# Copyright 2017 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "v3iod.cache.name" . }}
  labels:
    app: {{ template "v3iod.cache.name" . }}
    chart: {{ template "v3iod.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: locator
spec:
  selector:
    matchLabels:
      app: {{ template "v3iod.cache.name" . }}
      chart: {{ template "v3iod.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      component: locator
  template:
    metadata:
      labels:
        app: {{ template "v3iod.cache.name" . }}
        chart: {{ template "v3iod.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: locator
    spec:
      serviceAccountName: {{ template "v3iod.cache.name" . }}
      containers:
        - name: rest-locator
          image: {{ .Values.locator.image.repository }}:{{ .Values.locator.image.tag }}
          imagePullPolicy: {{ .Values.locator.image.pullPolicy | quote }}
          command: ["/bin/bash", "-c"]
          args:
            - locatorctl --namespace=$CURRENT_NAMESPACE
          ports:
            - containerPort: 8080
          resources:
{{ toYaml .Values.locator.resources | indent 12 }}
          env:
            - name: CURRENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
{{- with .Values.locator.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.locator.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.locator.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- if .Values.locator.priorityClassName }}
      priorityClassName: {{ .Values.locator.priorityClassName | quote }}
{{- end }}
