{{- if .Values.job.flexVolume.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "iguazio-system.flex-volume.name" . }}
  namespace: {{ .Values.tenant.name }}
  labels:
    app: {{ template "iguazio-system.name" . }}
    chart: {{ template "iguazio-system.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: flex-volume-plugin
data:
  v3io.conf: |
    {
      "fuse_path": "{{ .Values.job.flexVolume.executablePath }}",
      "image_repository": "{{ .Values.job.flexVolume.v3ioFuse.image.repository }}",
      "image_tag": "{{ .Values.job.flexVolume.v3ioFuse.image.tag }}",
      "type": "{{ .Values.job.flexVolume.mountType }}",
      "clusters": [
{{- range $index, $cluster := .Values.job.flexVolume.clusters }}
          {{- if gt $index 0 }},{{- end }}
          {
                "name": "{{ $cluster.name }}",
                "data_urls": [
{{- if $cluster.dataUrl  }}
                  "{{ $cluster.dataUrl }}"
{{- end  }}
{{- range $di, $dataUrl := $cluster.dataUrls }}
          {{- if gt $di 0 }},{{- end }}
                  "{{ $dataUrl }}"
{{- end  }}
                  ]
          }
{{- end }}
      ]
    }
{{- end -}}
