apiVersion: v1
kind: ConfigMap
metadata:
  name: presto.catalog
  labels:
    app: {{ template "presto.name" . }}
    chart: {{ template "presto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- $overrideHiveProperties := .Values.server.catalog.hive.override -}}
{{- if .Values.hive }}
{{- if not ($overrideHiveProperties) }}
  hive.properties: |
    connector.name=hive-hadoop2
    hive.metastore.uri=thrift://{{ .Values.hive.hostname }}:{{ .Values.hive.port }}
    hive.parquet.use-column-names=true
{{- if hasKey .Values.server.config.catalogs "hive.properties" }}
{{ print "======== Custom properties =========" | indent 4 }}
{{ index .Values.server.config.catalogs "hive.properties" | indent 4 }}
{{- end }}
{{- end }}
{{- end }}

{{- range $key, $val := .Values.server.config.catalogs }}
{{- if or (ne $key "hive.properties") $overrideHiveProperties }}
{{ printf "%s: |" $key | indent 2 }}
{{ $val | indent 4 }}
{{- end }}
{{- end }}
