apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "empty.name" . }}
  labels:
    app: {{ template "empty.name" . }}
    chart: {{ template "empty.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: daemon
data: ~
