tsdb:
  path: mytsdb
webapi:
  url: localhost:8081
  auth:
    username: iguazio
    password: iguazio
project:
  displayName: TSDB functions
functions:
    ingest:
      replicas: 1
      port: 32030
      ingress: {}
      image:
        repository: iguaziodocker/tsdb-ingest
        tag: 0.0.3
    query:
      replicas: 1
      port: 32031
      ingress: {}
      image:
        repository: iguaziodocker/tsdb-query
        tag: 0.0.3
