tsdb:
  container: bigdata
  path: mytsdb
webapi:
  url: v3io-webapi:8081
  auth:
    username: iguazio
    password: iguazio
    accessKeySecretName: ""
project:
  displayName: TSDB functions
functions:
    ingest:
      readinessTimeoutSeconds: 180
      replicas: 1
      port: 32030
      ingress: {}
      image:
        repository: quay.io/iguazio/tsdb-ingest
        tag: 0.0.12
    query:
      readinessTimeoutSeconds: 180
      replicas: 1
      port: 32031
      ingress: {}
      image:
        repository: quay.io/iguazio/tsdb-query
        tag: 0.0.12
