# Copyright 2017 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Default values for tenant.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: iguazio

namespace:
  create: true
  tagJob:
    run: false
    image:
      repository: lachlanevenson/k8s-kubectl
      tag: v1.9.8
      pullPolicy: IfNotPresent
    tag: owner

compute:
  create: true
  requests:
    cpu: 32
    memory: 80Gi
  limits:
    cpu: 128
    memory: 90Gi
  container:
    cpu:
      default: 4
      defaultRequest: 0.5
      min: 0.1
      max: 16
    memory:
      # This is the default limit; setting a low bar will require adding limit to all containers
      default: 4Gi
      defaultRequest: 16Mi
      min: 16Mi
      max: 16Gi

network:
  create: true
  ingress:
    allowedNamespaces: []
    # Namespaced allowed to access your tenant network
    #  - kube-system
  egress:
    limited: false

services:
  nodePorts: 0
  loadBalancers: 0

security:
  enabled: false
  privileged: false
  hostIPC: false
  hostPID: false
  hostNetwork: false
  allowPrivilegeEscalation: false
  allowedHostPaths:
    - /tmp
  dropCapabilities: {}
  # We should limit the capabilities with the following list (ALL is always dropped)
  #  - CAP_AUDIT_WRITE
  #  - CAP_IPC_OWNER
  #  - CAP_KILL
  #  - CAP_MAC_ADMIN
  #  - CAP_MAC_OVERRIDE
  #  - CAP_NET_ADMIN
  #  - CAP_NET_BIND_SERVICE
  #  - CAP_SYS_ADMIN
  #  - CAP_SYS_CHROOT
  #  - CAP_SYS_MODULE
  #  - CAP_SYS_NICE
  #  - CAP_SYS_TIME
  volumes: {}
  # Less is better: e.g. :
  #  - configMap
  #  - emptyDir
  #  - secret
  #  - flexVolume
  allowedFlexVolumes: {}

nodeSelector: {}

tolerations: []

affinity: {}
