# Default values for pod-gpu-metrics-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  type: ClusterIP
  port: 8080
  protocol: TCP

container:
  port: 8080

podGPUMetricsExporter:
  image:
    repository: "nvidia/pod-gpu-metrics-exporter"
    tag: "v1.0.0-alpha"

dcgmExporter:
  image:
    repository: "nvidia/dcgm-exporter"
    tag: "1.4.6"
